title: Jupiter Beachside Getaway
email: rob@robm.info
description: >-
  Experience an idyllic coastal retreat in Jupiter, FL. Steps from the shoreline and pet-friendly!
baseurl: "/Claud-rmmbeachside"
url: "https://romorris.github.io"
remote_theme: pages-themes/minimal@v0.2.0

# Navigation
nav:
  - name: Home
    link: /
  - name: Condo Info
    link: /JORC/
  - name: Dog Beach
    link: /dog_beach/
  - name: Dining
    link: /restaurants/
  - name: Contact
    link: /contact/

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
